/** Local opt-in diagnostics. Never accepts content, paths or application IDs. */
export type PerformanceStage = "startup" | "checkpoint" | "project-location" | "send-prepare" | "dispatch" | "host-ack" | "provider-first-event" | "renderer-receive" | "first-paint" | "last-paint" | "session-load" | "session-save" | "remote-sync" | "attachment-upload" | "attachment-preview" | "markdown-render" | "composer-resize" | "turn-grouping";
export type PerformanceMetrics = Partial<Record<"bytes" | "blocks" | "sessions" | "items" | "revision" | "backlog" | "cacheHit" | "phase" | "correlationId" | "checkpointWaitMs" | "gitMs" | "diskMs", number>>;
export type PerformanceTraceRecord = { stage: PerformanceStage; at: number; duration?: number; traceId?: string; metrics: PerformanceMetrics };
const metricKeys = new Set(["bytes", "blocks", "sessions", "items", "revision", "backlog", "cacheHit", "phase", "correlationId", "checkpointWaitMs", "gitMs", "diskMs"]);
const stages = new Set<string>(["startup", "checkpoint", "project-location", "send-prepare", "dispatch", "host-ack", "provider-first-event", "renderer-receive", "first-paint", "last-paint", "session-load", "session-save", "remote-sync", "attachment-upload", "attachment-preview", "markdown-render", "composer-resize", "turn-grouping"]);
let enabled = false;
let capacity = 2048;
let records: PerformanceTraceRecord[] = [];
let sequence = 0;
const sessionTraces = new Map<string, string>();
const SESSION_TRACE_LIMIT = 128;
/** Raw session keys stay local and are never included in exported records. */
export function beginSessionPerformanceTrace(sessionId: string): string | undefined {
  if (!enabled) return undefined;
  const traceId = createPerformanceTraceId();
  sessionTraces.delete(sessionId);
  sessionTraces.set(sessionId, traceId);
  while (sessionTraces.size > SESSION_TRACE_LIMIT) sessionTraces.delete(sessionTraces.keys().next().value!);
  return traceId;
}
export function sessionPerformanceTrace(sessionId: string): string | undefined { return enabled ? sessionTraces.get(sessionId) : undefined; }
export function endSessionPerformanceTrace(sessionId: string, traceId?: string): void {
  if (traceId === undefined || sessionTraces.get(sessionId) === traceId) sessionTraces.delete(sessionId);
}
export function isPerformanceTracingEnabled(): boolean { return enabled; }
export function setPerformanceVisualEffects(options: { shimmer?: boolean; blur?: boolean }): void {
  if (typeof document === "undefined") return;
  if (options.shimmer !== undefined) document.documentElement.toggleAttribute("data-performance-no-shimmer", !options.shimmer);
  if (options.blur !== undefined) document.documentElement.toggleAttribute("data-performance-no-blur", !options.blur);
}
export function createPerformanceTraceId(): string { return `trace-${++sequence}`; }
export function configurePerformanceTracing(options: { enabled: boolean; capacity?: number }): void {
  enabled = options.enabled;
  if (!enabled) sessionTraces.clear();
  capacity = Math.max(1, Math.min(10000, Math.floor(options.capacity ?? 2048) || 2048));
  records = records.slice(-capacity);
}
export function clearPerformanceTrace(): void { records = []; sessionTraces.clear(); }
export function getPerformanceTrace(): PerformanceTraceRecord[] { return records.map(record => ({ ...record, metrics: { ...record.metrics } })); }
function append(stage: PerformanceStage, at: number, metrics: PerformanceMetrics = {}, traceId?: string, duration?: number): void {
  if (!stages.has(stage)) return;
  const safe: PerformanceMetrics = {};
  for (const [key, value] of Object.entries(metrics)) {
    if (metricKeys.has(key) && typeof value === "number" && Number.isFinite(value)) safe[key as keyof PerformanceMetrics] = value;
  }
  // Only IDs generated by this collector may be exported.
  records.push({ stage, at, metrics: safe, ...(duration === undefined ? {} : { duration }), ...(traceId && /^trace-\d+$/.test(traceId) ? { traceId } : {}) });
  if (records.length > capacity) records.splice(0, records.length - capacity);
}
export function recordPerformanceEvent(stage: PerformanceStage, metrics?: PerformanceMetrics, traceId?: string): void {
  if (enabled) append(stage, performance.now(), metrics, traceId);
}
const noop = () => {};
export function startPerformanceSpan(stage: PerformanceStage, metrics?: PerformanceMetrics, traceId?: string): (finalMetrics?: PerformanceMetrics) => void {
  if (!enabled) return noop;
  const at = performance.now();
  let ended = false;
  return finalMetrics => {
    if (ended || !enabled) return;
    ended = true;
    append(stage, at, { ...metrics, ...finalMetrics }, traceId, Math.max(0, performance.now() - at));
  };
}
